# Generated by Django 3.0.1 on 2021-08-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210816_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Osos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceId', models.CharField(max_length=100, verbose_name='deviceId')),
                ('deviceDatetime', models.CharField(max_length=30, verbose_name='deviceDatetime')),
                ('meterSerial', models.CharField(max_length=30, verbose_name='meterSerial')),
                ('meterDate', models.CharField(max_length=30, verbose_name='meterDate')),
                ('meterTime', models.CharField(max_length=30, verbose_name='meterTime')),
                ('meterId', models.CharField(max_length=30, verbose_name='meterId')),
                ('bpResetCnt', models.CharField(max_length=30, verbose_name='bpResetCnt')),
                ('posActiveEnergy', models.CharField(max_length=30, verbose_name='posActiveEnergy')),
                ('posActiveEnergyT1', models.CharField(max_length=30, verbose_name='posActiveEnergyT1')),
                ('posActiveEnergyT2', models.CharField(max_length=30, verbose_name='posActiveEnergyT2')),
                ('posActiveEnergyT3', models.CharField(max_length=30, verbose_name='posActiveEnergyT3')),
                ('posActiveEnergyT4', models.CharField(max_length=30, verbose_name='posActiveEnergyT4')),
                ('negActiveEnergy', models.CharField(max_length=30, verbose_name='negActiveEnergy')),
                ('negActiveEnergyT1', models.CharField(max_length=30, verbose_name='negActiveEnergyT1')),
                ('negActiveEnergyT2', models.CharField(max_length=30, verbose_name='negActiveEnergyT2')),
                ('negActiveEnergyT3', models.CharField(max_length=30, verbose_name='negActiveEnergyT3')),
                ('negActiveEnergyT4', models.CharField(max_length=30, verbose_name='negActiveEnergyT4')),
                ('curP1', models.CharField(max_length=30, verbose_name='curP1')),
                ('voltP1', models.CharField(max_length=30, verbose_name='voltP1')),
                ('powFactorP1', models.CharField(max_length=30, verbose_name='powFactorP1')),
                ('curP2', models.CharField(max_length=30, verbose_name='curP2')),
                ('voltP2', models.CharField(max_length=30, verbose_name='voltP2')),
                ('powFactorP2', models.CharField(max_length=30, verbose_name='powFactorP2')),
                ('curP3', models.CharField(max_length=30, verbose_name='curP3')),
                ('voltP3', models.CharField(max_length=30, verbose_name='voltP3')),
                ('powFactorP3', models.CharField(max_length=30, verbose_name='powFactorP3')),
                ('importedInductiveReactiveEnergy', models.CharField(max_length=30, verbose_name='importedInductiveReactiveEnergy')),
                ('exportedInductiveReactiveEnergy', models.CharField(max_length=30, verbose_name='exportedInductiveReactiveEnergy')),
            ],
            options={
                'verbose_name': 'Osos',
                'verbose_name_plural': 'OsosData',
            },
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
    ]
